name: basic_flutter_theme
description: Flutter basic theme.
version: 1.0.7
homepage: https://github.com/nghetien/basic_flutter_theme

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0 # Update lên là hẹo
  fluttertoast: ^8.2.2
  logger: ^1.4.0
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  shimmer: ^3.0.0
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^8.0.0 # Update lên là hẹo
  collection: ^1.17.0 # Update lên là hẹo
  equatable: ^2.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
