name: basic_flutter_theme
description: Flutter basic theme.
version: 0.0.3
homepage: https://github.com/nghetien/basic_flutter_theme

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  fluttertoast: ^8.1.2
  logger: ^1.1.0
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.5
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
