name: basic_flutter_theme
description: Flutter basic theme.
version: 0.1.20
homepage: https://github.com/nghetien/basic_flutter_theme

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  fluttertoast: ^8.2.1
  logger: ^1.3.0
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  shimmer: ^2.0.0
  flutter_dotenv: ^5.0.2
  syncfusion_flutter_calendar: ^20.4.54

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
